%
(Generated by SketchUcam V1.3a)
(File: DrillJig.skp)
(Bit diameter: 2.5mm)
(Feed rate: 500.0mm/min)
(Plunge Feed rate: 200.0mm/min)
(Material Thickness: 3.2mm)
(Material length: 558.8mm X width: 1066.8mm)
(Overhead Gantry: true)
(Optimization is ON)
(www.PhlatBoyz.com)
G90 G21 G49  G17
M3 S20000
G00 Z10.000
 X58.189 Y55.240
(plungebore  DEPTH=3.520  DIAM=2.500)
G00 Z3.333
G01 Z-3.520 F200 
G00 Z3.333
G00 Y55.240 Z10.000
(plungebore end)
G00 X0 Y0 (home)
M05
M30
%
