%
(Generated by SketchUcam {1.2b1})
(File: Router Plates.skp)
(Bit diameter: 3.0mm)
(Feed rate: 2000.0mm/min)
(Plunge Feed rate: 1000.0mm/min)
(Material Thickness: 3.4mm)
(Material length: 600.0mm X width: 300.0mm)
(Overhead Gantry: true)
(Retract feed rate NOT limited to plunge feed rate)
(Multipass enabled, Depth = 0.1mm)
(Optimization is ON)
(www.PhlatBoyz.com)
G90 G21 G49 
M3 S11000
G0   Z5.000     
G0 X0 Y0 (home)
M05
M30
%
